//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class GameAreas : MonoBehaviour
{
	public const string CLASSROOM = "classroom";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string CLASSROOM_RED = "classroom_red";
	public GameObject classroomRed;
	public GameObject classroomRedNav;

	public const string CLASSROOM_BLUE = "classroom_blue";
	public GameObject classroomBlue;
	public GameObject classroomBlueNav;
}