//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class GameAreas : MonoBehaviour
{
	public const string ENTRACE_1 = "classroom";
	public GameObject entrace1;
	public GameObject entrace1;

	public const string ENTRANCE_2 = "ENTRANCE_2";
	public GameObject entrace2;
	public GameObject classroomNav;

	public const string ENTRACE_OUTSIDE = "ENTRACE_OUTSIDE";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string BEACH = "BEACH";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string FLORIST = "FLORIST";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string PALETTE = "PALETTE";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string BOTTOM_LEFT_1 = "BOTTOM_LEFT_1";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string BOTTOM_LEFT_2 = "BOTTOM_LEFT_2";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string CLASSROOM = "CLASSROOM";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string LEFT_MID_2 = "LEFT_MID_2";
	public GameObject classroom;
	public GameObject classroomNav;

	public const string RIGHT_MID_1 = "RIGHT_MID_1";
	public GameObject classroom;
	public GameObject classroomNav;
	
	public const string RIGHT_MID_2 = "RIGHT_MID_2";
	public GameObject classroom;
	public GameObject classroomNav;
	
	public const string TOP_LEFT_2 = "TOP_LEFT_2";
	public GameObject classroom;
	public GameObject classroomNav;
	
	public const string CAFE_INSIDE = "CAFE_INSIDE";
	public GameObject classroom;
	public GameObject classroomNav;
	
	public const string CAFE_OUTSIDE = "CAFE_OUTSIDE";
	public GameObject classroom;
	public GameObject classroomNav;
	
	public const string ZEN = "ZEN";
	public GameObject classroom;
	public GameObject classroomNav;

}